DROP TABLE IF EXISTS User CASCADE;

CREATE TABLE User (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Course CASCADE;

CREATE TABLE Course (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(500)
);

DROP TABLE IF EXISTS Enrollment;

CREATE TABLE Enrollment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    fk_user BIGINT NOT NULL,
    fk_course BIGINT NOT NULL,
    creation_date TIMESTAMP NOT NULL
);

ALTER TABLE Enrollment
    ADD FOREIGN KEY (fk_user)
    REFERENCES User(id)
    ON DELETE CASCADE;

ALTER TABLE Enrollment
    ADD FOREIGN KEY (fk_course)
    REFERENCES Course(id)
    ON DELETE CASCADE;
